# Generated by Django 6.0.2 on 2026-02-27 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('Position', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Department', models.CharField(max_length=100)),
                ('Office365ID', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestigationProcess',
            fields=[
                ('InvestigationID', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.TextField()),
                ('Conclusion', models.TextField(blank=True, null=True)),
                ('Status', models.CharField(max_length=50)),
                ('LastUpdatetByID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_last_updated_by', to='RH.users')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_user', to='RH.users')),
            ],
        ),
        migrations.CreateModel(
            name='InvestigationAttachments',
            fields=[
                ('AttachmentID', models.AutoField(primary_key=True, serialize=False)),
                ('OriginalFileName', models.CharField(max_length=255)),
                ('StoredFileName', models.CharField(max_length=255)),
                ('Token', models.CharField(max_length=255)),
                ('UploadedAt', models.DateTimeField(auto_now_add=True)),
                ('InvestigationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RH.investigationprocess')),
                ('UploadedByID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RH.users')),
            ],
        ),
        migrations.CreateModel(
            name='Warnings',
            fields=[
                ('AdvertenciaID', models.AutoField(primary_key=True, serialize=False)),
                ('IncidentDate', models.DateField()),
                ('Description', models.TextField()),
                ('OfficialText', models.TextField()),
                ('CurrentStage', models.CharField(max_length=50)),
                ('SchenduledDate', models.DateField()),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RH.employees')),
                ('WarningUserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RH.users')),
            ],
        ),
        migrations.CreateModel(
            name='WarningAttachments',
            fields=[
                ('AttachmentID', models.AutoField(primary_key=True, serialize=False)),
                ('FileName', models.CharField(max_length=255)),
                ('FilePath', models.CharField(max_length=255)),
                ('FileType', models.CharField(max_length=50)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('AdvertenciaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RH.warnings')),
            ],
        ),
        migrations.AddField(
            model_name='investigationprocess',
            name='AdvertenciaID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RH.warnings'),
        ),
        migrations.CreateModel(
            name='WarningWorkflow',
            fields=[
                ('WorkflowID', models.AutoField(primary_key=True, serialize=False)),
                ('Stage', models.CharField(max_length=50)),
                ('Comments', models.TextField(blank=True, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('AdvertenciaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RH.warnings')),
                ('WarningWorkflowUserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RH.users')),
            ],
        ),
    ]
