# Generated by Django 6.0.2 on 2026-02-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warningattachments',
            name='FilePath',
            field=models.FileField(upload_to='advertencias/anexos/'),
        ),
    ]
