# Generated by Django 6.0.3 on 2026-03-24 14:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0001_initial'),
        ('TI', '0003_gestorti_warningrequest_delete_colaborador_and_more'),
        ('comum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestorRH',
            fields=[
                ('GestorID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Office365ID', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('Active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gestor RH',
                'verbose_name_plural': 'Gestores RH',
                'db_table': 'RH_gestor_rh',
            },
        ),
        migrations.AlterField(
            model_name='warnings',
            name='ColaboradorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rh_warnings', to='comum.colaborador'),
        ),
        migrations.RemoveField(
            model_name='warnings',
            name='WarningUserID',
        ),
        migrations.RemoveField(
            model_name='warningworkflow',
            name='WarningWorkflowUserID',
        ),
        migrations.AlterModelOptions(
            name='investigationattachments',
            options={'verbose_name': 'Anexo de Investigação', 'verbose_name_plural': 'Anexos de Investigação'},
        ),
        migrations.AlterModelOptions(
            name='investigationprocess',
            options={'verbose_name': 'Processo de Investigação', 'verbose_name_plural': 'Processos de Investigação'},
        ),
        migrations.AlterModelOptions(
            name='warningattachments',
            options={'verbose_name': 'Anexo', 'verbose_name_plural': 'Anexos'},
        ),
        migrations.AlterModelOptions(
            name='warnings',
            options={'verbose_name': 'Advertência', 'verbose_name_plural': 'Advertências'},
        ),
        migrations.AlterModelOptions(
            name='warningworkflow',
            options={'verbose_name': 'Histórico de Workflow', 'verbose_name_plural': 'Históricos de Workflow'},
        ),
        migrations.AddField(
            model_name='investigationprocess',
            name='CreatedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investigationprocess',
            name='UpdatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='warnings',
            name='DepartmentOrigin',
            field=models.CharField(default='TI', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warnings',
            name='GestorOriginID',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warnings',
            name='CurrentStage',
            field=models.CharField(choices=[('criada', 'Solicitação Criada'), ('analise_rh', 'Em Análise RH'), ('analise_diretoria', 'Em Análise Diretoria'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada'), ('agendada', 'Agendada'), ('cancelada', 'Cancelada'), ('concluida', 'Concluída')], default='criada', max_length=50),
        ),
        migrations.AlterField(
            model_name='warnings',
            name='OfficialText',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='warnings',
            name='SchenduledDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='warningworkflow',
            name='AdvertenciaID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_history', to='RH.warnings'),
        ),
        migrations.AlterField(
            model_name='warningworkflow',
            name='Stage',
            field=models.CharField(choices=[('criada', 'Solicitação Criada'), ('revisa_rh', 'RH Revisou'), ('envia_diretoria', 'RH Enviou para Diretoria'), ('diretoria_aprova', 'Diretoria Aprovou'), ('diretoria_reprova', 'Diretoria Reprovou'), ('rh_agenda', 'RH Agendou'), ('rh_cancela', 'RH Cancelou'), ('concluida', 'Concluída')], max_length=50),
        ),
        migrations.AlterModelTable(
            name='investigationattachments',
            table='RH_investigation_attachments',
        ),
        migrations.AlterModelTable(
            name='investigationprocess',
            table='RH_investigation_process',
        ),
        migrations.AlterModelTable(
            name='warningattachments',
            table='RH_warning_attachments',
        ),
        migrations.AlterModelTable(
            name='warnings',
            table='RH_warnings',
        ),
        migrations.AlterModelTable(
            name='warningworkflow',
            table='RH_warning_workflow',
        ),
        migrations.AddField(
            model_name='warnings',
            name='GestorRH',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RH.gestorrh'),
        ),
        migrations.AddField(
            model_name='warningworkflow',
            name='GestorRH',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RH.gestorrh'),
        ),
        migrations.AlterField(
            model_name='investigationattachments',
            name='UploadedByID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RH.gestorrh'),
        ),
        migrations.AlterField(
            model_name='investigationprocess',
            name='LastUpdatetByID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_last_updated_by', to='RH.gestorrh'),
        ),
        migrations.AlterField(
            model_name='investigationprocess',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_user', to='RH.gestorrh'),
        ),
        migrations.DeleteModel(
            name='Colaborador',
        ),
        migrations.DeleteModel(
            name='Gestor',
        ),
    ]
