# Generated by Django 6.0.3 on 2026-04-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0003_warnings_gestor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warnings',
            name='CurrentStage',
            field=models.CharField(choices=[('Solicitada', 'Solicitação Criada'), ('analise_rh', 'Em Análise RH'), ('analise_diretoria', 'Em Análise Diretoria'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada'), ('agendada', 'Agendada'), ('cancelada', 'Cancelada'), ('concluida', 'Concluída')], default='criada', max_length=50),
        ),
    ]
