# Generated by Django 6.0.2 on 2026-03-03 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0003_alter_warnings_warninguserid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warnings',
            name='WarningUserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RH.users'),
        ),
        migrations.AlterField(
            model_name='warningworkflow',
            name='WarningWorkflowUserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RH.users'),
        ),
    ]
