# Generated by Django 6.0.3 on 2026-04-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0004_alter_warnings_currentstage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warnings',
            name='GestorOriginID',
        ),
    ]
