# Generated by Django 6.0.3 on 2026-04-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0005_remove_warnings_gestororiginid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warnings',
            name='CurrentStage',
            field=models.CharField(choices=[('Solicitada', 'Solicitada'), ('Em Análise RH', 'Em Análise RH'), ('Em Análise Diretoria', 'Em Análise Diretoria'), ('Aprovada', 'Aprovada'), ('Em Sindicância', 'Em Sindicância'), ('Cancelada', 'Cancelada'), ('Concluída', 'Concluída')], max_length=50),
        ),
    ]
