# Generated by Django 6.0.3 on 2026-04-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0006_alter_warnings_currentstage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warnings',
            name='CurrentStage',
            field=models.CharField(choices=[('Solicitada', 'Solicitada'), ('Análise RH', 'Análise RH'), ('Análise Diretoria', 'Análise Diretoria'), ('Aprovada', 'Aprovada'), ('Sindicância', 'Sindicância'), ('Cancelada', 'Cancelada'), ('Concluída', 'Concluída')], max_length=50),
        ),
    ]
