# Generated by Django 6.0.3 on 2026-04-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GestorMarketing',
            fields=[
                ('GestorID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Office365ID', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('Active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gestor Marketing',
                'verbose_name_plural': 'Gestores Marketing',
                'db_table': 'Marketing_gestor_marketing',
            },
        ),
    ]
