# Generated by Django 6.0.3 on 2026-04-06 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing', '0001_initial'),
        ('comum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gestormarketing',
            table='marketing_gestor_marketing',
        ),
        migrations.CreateModel(
            name='WarningRequest',
            fields=[
                ('RequestID', models.AutoField(primary_key=True, serialize=False)),
                ('IncidentDate', models.DateField()),
                ('Description', models.TextField()),
                ('Status', models.CharField(choices=[('criada', 'Criada'), ('enviada_rh', 'Enviada para RH'), ('convertida', 'Convertida em Advertência'), ('processando', 'Processando')], default='criada', max_length=50)),
                ('AdvertenciaID', models.IntegerField(blank=True, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('ColaboradorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_warning_requests', to='comum.colaborador')),
                ('GestorMarketing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Marketing.gestormarketing')),
            ],
            options={
                'verbose_name': 'Solicitação de Advertência',
                'verbose_name_plural': 'Solicitações de Advertência',
                'db_table': 'marketing_warning_request',
            },
        ),
    ]
