# Generated by Django 6.0.3 on 2026-03-13 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0001_initial'),
        ('TI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warnings',
            name='ColaboradorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ti_warnings', to='RH.colaborador'),
        ),
    ]
