# Generated by Django 6.0.3 on 2026-03-24 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TI', '0002_alter_warnings_colaboradorid'),
        ('comum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestorTI',
            fields=[
                ('GestorID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Office365ID', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('Active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gestor TI',
                'verbose_name_plural': 'Gestores TI',
                'db_table': 'TI_gestor_ti',
            },
        ),
        migrations.CreateModel(
            name='WarningRequest',
            fields=[
                ('RequestID', models.AutoField(primary_key=True, serialize=False)),
                ('IncidentDate', models.DateField()),
                ('Description', models.TextField()),
                ('Status', models.CharField(choices=[('criada', 'Criada'), ('enviada_rh', 'Enviada para RH'), ('convertida', 'Convertida em Advertência'), ('processando', 'Processando')], default='criada', max_length=50)),
                ('AdvertenciaID', models.IntegerField(blank=True, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('ColaboradorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ti_warning_requests', to='comum.colaborador')),
                ('GestorTI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TI.gestorti')),
            ],
            options={
                'verbose_name': 'Solicitação de Advertência',
                'verbose_name_plural': 'Solicitações de Advertência',
                'db_table': 'TI_warning_request',
            },
        ),
        migrations.DeleteModel(
            name='Colaborador',
        ),
        migrations.RemoveField(
            model_name='investigationprocess',
            name='LastUpdatetByID',
        ),
        migrations.RemoveField(
            model_name='warningworkflow',
            name='WarningWorkflowUserID',
        ),
        migrations.RemoveField(
            model_name='investigationprocess',
            name='UserID',
        ),
        migrations.RemoveField(
            model_name='warnings',
            name='WarningUserID',
        ),
        migrations.RemoveField(
            model_name='investigationattachments',
            name='UploadedByID',
        ),
        migrations.RemoveField(
            model_name='investigationattachments',
            name='InvestigationID',
        ),
        migrations.RemoveField(
            model_name='investigationprocess',
            name='WarningID',
        ),
        migrations.RemoveField(
            model_name='warningattachments',
            name='WarningID',
        ),
        migrations.RemoveField(
            model_name='warnings',
            name='ColaboradorID',
        ),
        migrations.RemoveField(
            model_name='warningworkflow',
            name='WarningID',
        ),
        migrations.DeleteModel(
            name='Gestor',
        ),
        migrations.DeleteModel(
            name='InvestigationAttachments',
        ),
        migrations.DeleteModel(
            name='InvestigationProcess',
        ),
        migrations.DeleteModel(
            name='WarningAttachments',
        ),
        migrations.DeleteModel(
            name='Warnings',
        ),
        migrations.DeleteModel(
            name='WarningWorkflow',
        ),
    ]
