# Generated by Django 6.0.3 on 2026-04-06 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestorFinanceiro',
            fields=[
                ('GestorID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Office365ID', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('Active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gestor Financeiro',
                'verbose_name_plural': 'Gestores Financeiro',
                'db_table': 'financeiro_gestor_financeiro',
            },
        ),
        migrations.CreateModel(
            name='WarningRequest',
            fields=[
                ('RequestID', models.AutoField(primary_key=True, serialize=False)),
                ('IncidentDate', models.DateField()),
                ('Description', models.TextField()),
                ('Status', models.CharField(choices=[('criada', 'Criada'), ('enviada_rh', 'Enviada para RH'), ('convertida', 'Convertida em Advertência'), ('processando', 'Processando')], default='criada', max_length=50)),
                ('AdvertenciaID', models.IntegerField(blank=True, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('ColaboradorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financeiro_warning_requests', to='comum.colaborador')),
                ('GestorFinanceiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Financeiro.gestorfinanceiro')),
            ],
            options={
                'verbose_name': 'Solicitação de Advertência',
                'verbose_name_plural': 'Solicitações de Advertência',
                'db_table': 'financeiro_warning_request',
            },
        ),
    ]
