# Generated by Django 6.0.2 on 2026-02-27 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tela_login_microsoft', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Advertencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaborador_nome', models.CharField(max_length=255)),
                ('colaborador_id_folha', models.CharField(max_length=50, verbose_name='ID ou Matrícula')),
                ('motivo', models.TextField()),
                ('data_ocorrencia', models.DateField()),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('gravidade', models.CharField(choices=[('Leve', 'Leve'), ('Média', 'Média'), ('Grave', 'Grave')], default='Leve', max_length=10)),
                ('status', models.CharField(choices=[('Solicitada', 'Solicitada'), ('Em Análise RH', 'Em Análise RH'), ('Em Análise Diretoria', 'Em Análise Diretoria'), ('Aprovada', 'Aprovada'), ('Concluída', 'Concluída')], default='Solicitada', max_length=30)),
                ('observacao_rh', models.TextField(blank=True, null=True, verbose_name='Observações do RH')),
                ('anexo', models.FileField(blank=True, null=True, upload_to='advertencias/provas/')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advertencias_criadas', to=settings.AUTH_USER_MODEL)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tela_login_microsoft.departamento')),
            ],
            options={
                'verbose_name': 'Advertência',
                'verbose_name_plural': 'Advertências',
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
